import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import tailwindcss from '@tailwindcss/vite';
import rehypeKatex from 'rehype-katex';
import remarkMath from 'remark-math';

export default defineConfig({
  site: 'https://asgoshawk.github.io',
  base: '/leetcode-handbook',
  vite: {
    plugins: [tailwindcss()],
  },
  markdown: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [rehypeKatex],
  },
  integrations: [
    starlight({
      title: 'LeetCode 自學手冊',
      description: '以臺灣繁體中文整理的資料結構與演算法自學手冊',
      defaultLocale: 'root',
      locales: {
        root: { label: '繁體中文', lang: 'zh-TW' },
      },
      social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/asgoshawk/leetcode-handbook' }],
      editLink: { baseUrl: 'https://github.com/asgoshawk/leetcode-handbook/edit/main/' },
      customCss: ['./src/styles/custom.css'],
      head: [
        {
          tag: 'script',
          content: "try{if(!localStorage.getItem('starlight-theme')){localStorage.setItem('starlight-theme','dark');document.documentElement.dataset.theme='dark'}}catch(e){}",
        },
      ],
      sidebar: [
        { label: '開始使用', items: [
          { label: '手冊首頁', slug: 'index' },
          { label: '學習路線', slug: 'learning-path' },
          { label: '如何新增題解', slug: 'contributing' },
        ] },
        { label: '題解', items: [
          { label: '題目索引', slug: 'problems' },
          { label: 'Easy', items: [
            { label: '1. Two Sum', slug: 'problems/0001-two-sum' },
            { label: '20. Valid Parentheses', slug: 'problems/0020-valid-parentheses' },
            { label: '21. Merge Two Sorted Lists', slug: 'problems/0021-merge-two-sorted-lists' },
            { label: '26. Remove Duplicates from Sorted Array', slug: 'problems/0026-remove-duplicates-from-sorted-array' },
            { label: '35. Search Insert Position', slug: 'problems/0035-search-insert-position' },
            { label: '66. Plus One', slug: 'problems/0066-plus-one' },
            { label: '70. Climbing Stairs', slug: 'problems/0070-climbing-stairs' },
            { label: '100. Same Tree', slug: 'problems/0100-same-tree' },
            { label: '104. Maximum Depth of Binary Tree', slug: 'problems/0104-maximum-depth-of-binary-tree' },
            { label: '118. Pascal\'s Triangle', slug: 'problems/0118-pascals-triangle' },
            { label: '121. Best Time to Buy and Sell Stock', slug: 'problems/0121-best-time-to-buy-and-sell-stock' },
            { label: '125. Valid Palindrome', slug: 'problems/0125-valid-palindrome' },
            { label: '136. Single Number', slug: 'problems/0136-single-number' },
            { label: '169. Majority Element', slug: 'problems/0169-majority-element' },
            { label: '191. Number of 1 Bits', slug: 'problems/0191-number-of-1-bits' },
            { label: '206. Reverse Linked List', slug: 'problems/0206-reverse-linked-list' },
            { label: '217. Contains Duplicate', slug: 'problems/0217-contains-duplicate' },
            { label: '226. Invert Binary Tree', slug: 'problems/0226-invert-binary-tree' },
            { label: '242. Valid Anagram', slug: 'problems/0242-valid-anagram' },
            { label: '268. Missing Number', slug: 'problems/0268-missing-number' },
            { label: '283. Move Zeroes', slug: 'problems/0283-move-zeroes' },
            { label: '704. Binary Search', slug: 'problems/0704-binary-search' },
            { label: '733. Flood Fill', slug: 'problems/0733-flood-fill' },
          ] },
          { label: 'Medium', items: [
            { label: '3. Longest Substring Without Repeating Characters', slug: 'problems/0003-longest-substring-without-repeating-characters' },
            { label: '5. Longest Palindromic Substring', slug: 'problems/0005-longest-palindromic-substring' },
            { label: '11. Container With Most Water', slug: 'problems/0011-container-with-most-water' },
            { label: '15. 3Sum', slug: 'problems/0015-3sum' },
            { label: '17. Letter Combinations of a Phone Number', slug: 'problems/0017-letter-combinations-of-a-phone-number' },
            { label: '33. Search in Rotated Sorted Array', slug: 'problems/0033-search-in-rotated-sorted-array' },
            { label: '39. Combination Sum', slug: 'problems/0039-combination-sum' },
            { label: '46. Permutations', slug: 'problems/0046-permutations' },
            { label: '49. Group Anagrams', slug: 'problems/0049-group-anagrams' },
            { label: '53. Maximum Subarray', slug: 'problems/0053-maximum-subarray' },
            { label: '54. Spiral Matrix', slug: 'problems/0054-spiral-matrix' },
            { label: '56. Merge Intervals', slug: 'problems/0056-merge-intervals' },
            { label: '62. Unique Paths', slug: 'problems/0062-unique-paths' },
            { label: '73. Set Matrix Zeroes', slug: 'problems/0073-set-matrix-zeroes' },
            { label: '75. Sort Colors', slug: 'problems/0075-sort-colors' },
            { label: '78. Subsets', slug: 'problems/0078-subsets' },
            { label: '90. Subsets II', slug: 'problems/0090-subsets-ii' },
            { label: '98. Validate Binary Search Tree', slug: 'problems/0098-validate-binary-search-tree' },
            { label: '102. Binary Tree Level Order Traversal', slug: 'problems/0102-binary-tree-level-order-traversal' },
            { label: '139. Word Break', slug: 'problems/0139-word-break' },
            { label: '153. Find Minimum in Rotated Sorted Array', slug: 'problems/0153-find-minimum-in-rotated-sorted-array' },
            { label: '167. Two Sum II - Input Array Is Sorted', slug: 'problems/0167-two-sum-ii-input-array-is-sorted' },
            { label: '198. House Robber', slug: 'problems/0198-house-robber' },
            { label: '200. Number of Islands', slug: 'problems/0200-number-of-islands' },
            { label: '207. Course Schedule', slug: 'problems/0207-course-schedule' },
            { label: '209. Minimum Size Subarray Sum', slug: 'problems/0209-minimum-size-subarray-sum' },
            { label: '238. Product of Array Except Self', slug: 'problems/0238-product-of-array-except-self' },
            { label: '300. Longest Increasing Subsequence', slug: 'problems/0300-longest-increasing-subsequence' },
            { label: '322. Coin Change', slug: 'problems/0322-coin-change' },
            { label: '347. Top K Frequent Elements', slug: 'problems/0347-top-k-frequent-elements' },
            { label: '560. Subarray Sum Equals K', slug: 'problems/0560-subarray-sum-equals-k' },
          ] },
          { label: 'Hard', items: [
            { label: '23. Merge k Sorted Lists', slug: 'problems/0023-merge-k-sorted-lists' },
            { label: '42. Trapping Rain Water', slug: 'problems/0042-trapping-rain-water' },
            { label: '76. Minimum Window Substring', slug: 'problems/0076-minimum-window-substring' },
            { label: '239. Sliding Window Maximum', slug: 'problems/0239-sliding-window-maximum' },
          ] },
        ] },
      ],
    }),
  ],
});
