import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import tailwindcss from '@tailwindcss/vite';
import rehypeKatex from 'rehype-katex';
import remarkMath from 'remark-math';

export default defineConfig({
  site: 'https://asgoshawk.github.io',
  base: '/leetcode-handbook',
  vite: {
    plugins: [tailwindcss()],
  },
  markdown: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [rehypeKatex],
  },
  integrations: [
    starlight({
      title: 'LeetCode 自學手冊',
      description: '以臺灣繁體中文整理的資料結構與演算法自學手冊',
      defaultLocale: 'root',
      locales: {
        root: { label: '繁體中文', lang: 'zh-TW' },
      },
      social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/asgoshawk/leetcode-handbook' }],
      editLink: { baseUrl: 'https://github.com/asgoshawk/leetcode-handbook/edit/main/' },
      customCss: ['./src/styles/custom.css'],
      head: [
        {
          tag: 'script',
          content: "try{if(!localStorage.getItem('starlight-theme')){localStorage.setItem('starlight-theme','dark');document.documentElement.dataset.theme='dark'}}catch(e){}",
        },
      ],
      sidebar: [
        { label: '開始使用', items: [
          { label: '手冊首頁', slug: 'index' },
          { label: '學習路線', slug: 'learning-path' },
          { label: '已閱覽題目', slug: 'viewed' },
          { label: '喜好題目', slug: 'favorites' },
          { label: '如何新增題解', slug: 'contributing' },
        ] },
        { label: '題解', items: [
          { label: '題目索引', slug: 'problems' },
          { label: 'Easy', items: [
            { label: '1. Two Sum', slug: 'problems/0001-two-sum' },
            { label: '14. Longest Common Prefix', slug: 'problems/0014-longest-common-prefix' },
            { label: '20. Valid Parentheses', slug: 'problems/0020-valid-parentheses' },
            { label: '21. Merge Two Sorted Lists', slug: 'problems/0021-merge-two-sorted-lists' },
            { label: '26. Remove Duplicates from Sorted Array', slug: 'problems/0026-remove-duplicates-from-sorted-array' },
            { label: '27. Remove Element', slug: 'problems/0027-remove-element' },
            { label: '35. Search Insert Position', slug: 'problems/0035-search-insert-position' },
            { label: '58. Length of Last Word', slug: 'problems/0058-length-of-last-word' },
            { label: '66. Plus One', slug: 'problems/0066-plus-one' },
            { label: '70. Climbing Stairs', slug: 'problems/0070-climbing-stairs' },
            { label: '83. Remove Duplicates from Sorted List', slug: 'problems/0083-remove-duplicates-from-sorted-list' },
            { label: '88. Merge Sorted Array', slug: 'problems/0088-merge-sorted-array' },
            { label: '100. Same Tree', slug: 'problems/0100-same-tree' },
            { label: '101. Symmetric Tree', slug: 'problems/0101-symmetric-tree' },
            { label: '104. Maximum Depth of Binary Tree', slug: 'problems/0104-maximum-depth-of-binary-tree' },
            { label: '110. Balanced Binary Tree', slug: 'problems/0110-balanced-binary-tree' },
            { label: '121. Best Time to Buy and Sell Stock', slug: 'problems/0121-best-time-to-buy-and-sell-stock' },
            { label: '125. Valid Palindrome', slug: 'problems/0125-valid-palindrome' },
            { label: '136. Single Number', slug: 'problems/0136-single-number' },
            { label: '171. Excel Sheet Column Number', slug: 'problems/0171-excel-sheet-column-number' },
            { label: '169. Majority Element', slug: 'problems/0169-majority-element' },
            { label: '190. Reverse Bits', slug: 'problems/0190-reverse-bits' },
            { label: '191. Number of 1 Bits', slug: 'problems/0191-number-of-1-bits' },
            { label: '202. Happy Number', slug: 'problems/0202-happy-number' },
            { label: '203. Remove Linked List Elements', slug: 'problems/0203-remove-linked-list-elements' },
            { label: '206. Reverse Linked List', slug: 'problems/0206-reverse-linked-list' },
            { label: '217. Contains Duplicate', slug: 'problems/0217-contains-duplicate' },
            { label: '226. Invert Binary Tree', slug: 'problems/0226-invert-binary-tree' },
            { label: '234. Palindrome Linked List', slug: 'problems/0234-palindrome-linked-list' },
            { label: '242. Valid Anagram', slug: 'problems/0242-valid-anagram' },
            { label: '268. Missing Number', slug: 'problems/0268-missing-number' },
            { label: '283. Move Zeroes', slug: 'problems/0283-move-zeroes' },
            { label: '338. Counting Bits', slug: 'problems/0338-counting-bits' },
            { label: '344. Reverse String', slug: 'problems/0344-reverse-string' },
            { label: '383. Ransom Note', slug: 'problems/0383-ransom-note' },
            { label: '387. First Unique Character in a String', slug: 'problems/0387-first-unique-character-in-a-string' },
            { label: '392. Is Subsequence', slug: 'problems/0392-is-subsequence' },
            { label: '509. Fibonacci Number', slug: 'problems/0509-fibonacci-number' },
            { label: '704. Binary Search', slug: 'problems/0704-binary-search' },
            { label: '733. Flood Fill', slug: 'problems/0733-flood-fill' },
          ] },
          { label: 'Medium', items: [
            { label: '3. Longest Substring Without Repeating Characters', slug: 'problems/0003-longest-substring-without-repeating-characters' },
            { label: '5. Longest Palindromic Substring', slug: 'problems/0005-longest-palindromic-substring' },
            { label: '11. Container With Most Water', slug: 'problems/0011-container-with-most-water' },
            { label: '15. 3Sum', slug: 'problems/0015-3sum' },
            { label: '17. Letter Combinations of a Phone Number', slug: 'problems/0017-letter-combinations-of-a-phone-number' },
            { label: '19. Remove Nth Node From End of List', slug: 'problems/0019-remove-nth-node-from-end-of-list' },
            { label: '22. Generate Parentheses', slug: 'problems/0022-generate-parentheses' },
            { label: '24. Swap Nodes in Pairs', slug: 'problems/0024-swap-nodes-in-pairs' },
            { label: '33. Search in Rotated Sorted Array', slug: 'problems/0033-search-in-rotated-sorted-array' },
            { label: '34. Find First and Last Position of Element in Sorted Array', slug: 'problems/0034-find-first-and-last-position-of-element-in-sorted-array' },
            { label: '36. Valid Sudoku', slug: 'problems/0036-valid-sudoku' },
            { label: '39. Combination Sum', slug: 'problems/0039-combination-sum' },
            { label: '40. Combination Sum II', slug: 'problems/0040-combination-sum-ii' },
            { label: '45. Jump Game II', slug: 'problems/0045-jump-game-ii' },
            { label: '46. Permutations', slug: 'problems/0046-permutations' },
            { label: '48. Rotate Image', slug: 'problems/0048-rotate-image' },
            { label: '49. Group Anagrams', slug: 'problems/0049-group-anagrams' },
            { label: '53. Maximum Subarray', slug: 'problems/0053-maximum-subarray' },
            { label: '54. Spiral Matrix', slug: 'problems/0054-spiral-matrix' },
            { label: '55. Jump Game', slug: 'problems/0055-jump-game' },
            { label: '56. Merge Intervals', slug: 'problems/0056-merge-intervals' },
            { label: '62. Unique Paths', slug: 'problems/0062-unique-paths' },
            { label: '73. Set Matrix Zeroes', slug: 'problems/0073-set-matrix-zeroes' },
            { label: '74. Search a 2D Matrix', slug: 'problems/0074-search-a-2d-matrix' },
            { label: '75. Sort Colors', slug: 'problems/0075-sort-colors' },
            { label: '78. Subsets', slug: 'problems/0078-subsets' },
            { label: '79. Word Search', slug: 'problems/0079-word-search' },
            { label: '90. Subsets II', slug: 'problems/0090-subsets-ii' },
            { label: '91. Decode Ways', slug: 'problems/0091-decode-ways' },
            { label: '98. Validate Binary Search Tree', slug: 'problems/0098-validate-binary-search-tree' },
            { label: '102. Binary Tree Level Order Traversal', slug: 'problems/0102-binary-tree-level-order-traversal' },
            { label: '103. Binary Tree Zigzag Level Order Traversal', slug: 'problems/0103-binary-tree-zigzag-level-order-traversal' },
            { label: '114. Flatten Binary Tree to Linked List', slug: 'problems/0114-flatten-binary-tree-to-linked-list' },
            { label: '128. Longest Consecutive Sequence', slug: 'problems/0128-longest-consecutive-sequence' },
            { label: '139. Word Break', slug: 'problems/0139-word-break' },
            { label: '152. Maximum Product Subarray', slug: 'problems/0152-maximum-product-subarray' },
            { label: '153. Find Minimum in Rotated Sorted Array', slug: 'problems/0153-find-minimum-in-rotated-sorted-array' },
            { label: '167. Two Sum II - Input Array Is Sorted', slug: 'problems/0167-two-sum-ii-input-array-is-sorted' },
            { label: '198. House Robber', slug: 'problems/0198-house-robber' },
            { label: '199. Binary Tree Right Side View', slug: 'problems/0199-binary-tree-right-side-view' },
            { label: '200. Number of Islands', slug: 'problems/0200-number-of-islands' },
            { label: '207. Course Schedule', slug: 'problems/0207-course-schedule' },
            { label: '209. Minimum Size Subarray Sum', slug: 'problems/0209-minimum-size-subarray-sum' },
            { label: '215. Kth Largest Element in an Array', slug: 'problems/0215-kth-largest-element-in-an-array' },
            { label: '230. Kth Smallest Element in a BST', slug: 'problems/0230-kth-smallest-element-in-a-bst' },
            { label: '238. Product of Array Except Self', slug: 'problems/0238-product-of-array-except-self' },
            { label: '279. Perfect Squares', slug: 'problems/0279-perfect-squares' },
            { label: '300. Longest Increasing Subsequence', slug: 'problems/0300-longest-increasing-subsequence' },
            { label: '322. Coin Change', slug: 'problems/0322-coin-change' },
            { label: '347. Top K Frequent Elements', slug: 'problems/0347-top-k-frequent-elements' },
            { label: '394. Decode String', slug: 'problems/0394-decode-string' },
            { label: '416. Partition Equal Subset Sum', slug: 'problems/0416-partition-equal-subset-sum' },
            { label: '560. Subarray Sum Equals K', slug: 'problems/0560-subarray-sum-equals-k' },
          ] },
          { label: 'Hard', items: [
            { label: '23. Merge k Sorted Lists', slug: 'problems/0023-merge-k-sorted-lists' },
            { label: '42. Trapping Rain Water', slug: 'problems/0042-trapping-rain-water' },
            { label: '76. Minimum Window Substring', slug: 'problems/0076-minimum-window-substring' },
            { label: '239. Sliding Window Maximum', slug: 'problems/0239-sliding-window-maximum' },
          ] },
        ] },
      ],
    }),
  ],
});
